package zartc.util;

import java.util.Collection;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Vector;

import org.apache.commons.lang3.builder.ToStringStyle;

/**
 * A customized ToStringStyle that displays more informations about the type of
 * field, arrays and collections. The format generated by this ToStringStyle
 * mimic the format generated by Spring's ToStringCreator.
 * 
 * @author Pascal JACOB
 */
public class SpringToStringStyle extends ToStringStyle {
	private static final long serialVersionUID = 1L;

	private static final String COLLECTION = "coll";
	private static final String VECTOR = "vector";
	private static final String SET = "set";
	private static final String LIST = "list";
	private static final String MAP = "map";
	private static final String ARRAY = "array";

	private Object stringStart = "\"";

	private Object stringEnd = "\"";

	public SpringToStringStyle() {
		setContentStart("{");
		setContentEnd("}");
		setArrayStart("[");
		setArrayEnd("]");
		setArraySeparator(",");
		setFieldSeparator(", ");
		setArrayContentDetail(true);
		setUseShortClassName(true);
		setUseIdentityHashCode(true);
	}

	protected void appendDetail(final StringBuffer buffer, final String fieldName, final Object value) {
		if (value instanceof String) {
			appendStringStart(buffer);
			buffer.append(value);
			appendStringEnd(buffer);
		} else
			super.appendDetail(buffer, fieldName, value);
	}

	private void appendStringStart(StringBuffer buffer) {
		buffer.append(stringStart);
	}

	private void appendStringEnd(StringBuffer buffer) {
		buffer.append(stringEnd);
	}

	@Override
	protected void appendDetail(StringBuffer buffer, String fieldName, boolean[] array) {
		buffer.append(ARRAY).append("<").append(getArrayType(array)).append(">");
		super.appendDetail(buffer, fieldName, array);
	}

	@Override
	protected void appendDetail(StringBuffer buffer, String fieldName, byte[] array) {
		buffer.append(ARRAY).append("<").append(getArrayType(array)).append(">");
		super.appendDetail(buffer, fieldName, array);
	}

	@Override
	protected void appendDetail(StringBuffer buffer, String fieldName, char[] array) {
		buffer.append(ARRAY).append("<").append(getArrayType(array)).append(">");
		super.appendDetail(buffer, fieldName, array);
	}

	@Override
	protected void appendDetail(StringBuffer buffer, String fieldName, double[] array) {
		buffer.append(ARRAY).append("<").append(getArrayType(array)).append(">");
		super.appendDetail(buffer, fieldName, array);
	}

	@Override
	protected void appendDetail(StringBuffer buffer, String fieldName, float[] array) {
		buffer.append(ARRAY).append("<").append(getArrayType(array)).append(">");
		super.appendDetail(buffer, fieldName, array);
	}

	@Override
	protected void appendDetail(StringBuffer buffer, String fieldName, int[] array) {
		buffer.append(ARRAY).append("<").append(getArrayType(array)).append(">");
		super.appendDetail(buffer, fieldName, array);
	}

	@Override
	protected void appendDetail(final StringBuffer buffer, final String fieldName, final long[] array) {
		buffer.append(ARRAY).append("<").append(getArrayType(array)).append(">");
		super.appendDetail(buffer, fieldName, array);
	}

	@Override
	protected void appendDetail(StringBuffer buffer, String fieldName, short[] array) {
		buffer.append(ARRAY).append("<").append(getArrayType(array)).append(">");
		super.appendDetail(buffer, fieldName, array);
	}

	@Override
	protected void appendDetail(StringBuffer buffer, String fieldName, Object[] array) {
		buffer.append(ARRAY).append("<").append(getArrayType(array)).append(">");
		super.appendDetail(buffer, fieldName, array);
	}

	@Override
	protected void reflectionAppendArrayDetail(StringBuffer buffer, String fieldName, Object array) {
		buffer.append(ARRAY).append("<").append(getArrayType(array)).append(">");
		super.reflectionAppendArrayDetail(buffer, fieldName, array);
	}

	@Override
	protected void appendDetail(StringBuffer buffer, String fieldName, Map<?, ?> map) {
		buffer.append(MAP);
		buffer.append(getArrayStart());

		for (Iterator<?> it = (Iterator<?>) map.entrySet().iterator(); it.hasNext();) {
			Object next = it.next();
			appendDetail(buffer, fieldName, ((Map.Entry<?, ?>) next).getKey());
			buffer.append("->");
			appendDetail(buffer, fieldName, ((Map.Entry<?, ?>) next).getValue());
			if (it.hasNext()) {
				buffer.append(getArraySeparator());
			}
		}
		buffer.append(getArrayEnd());
	}

	@Override
	protected void appendDetail(StringBuffer buffer, String fieldName, Collection<?> coll) {
		buffer.append(getCollectionTypeString(coll));
		super.appendDetail(buffer, fieldName, coll);
	}

	private String getCollectionTypeString(Collection<?> value) {
		if (value instanceof Vector) {
			return VECTOR;
		} else if (value instanceof List) {
			return LIST;
		} else if (value instanceof Set) {
			return SET;
		} else {
			return COLLECTION;
		}
	}
	
	private String getArrayType(Object array) {
		Class<?> componentType = array.getClass().getComponentType();
		return org.apache.commons.lang3.ClassUtils.getShortClassName(componentType);
	}
}
